### ISSUE TITLE
Livox question

### ISSUE THREAD

**Issue by MattiasTancred** [davidskdds/dense_cloud_creator#1]
Hello David,

I downloaded and ran the rosbag (via DMSA_LiDAR_SLAM) from here:
https://github.com/davidskdds/DMSA_LiDAR_SLAM/issues/3#issuecomment-2104354717

I have tried running the resulting Pose.txt and rosbag (sensor unknown) thru this repo with no luck. 
Do you have any suggestion, any guidance would be greatly appreciated.

**Comment by davidskdds** [comment]
Hello @MattiasTancred ,

I just tested your issue and I was able to reproduce it.
There was a bug in the "unknown" sensor config mode.

I could fix the bug and I also added a Livox configuration now.
The Livox configuration should create even better results than just using the heuristic stamps in the "unknown" mode.

It should now also work on your side.

Best regards
David
